version: '3.8'
services:
  elasticsearch1:
    image: elasticsearch:8.12.1
    container_name: elasticsearch1
    volumes: # 공통 변수
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      - ES_JAVA_OPTS=-Xms1024m -Xmx1024m
      - xpack.security.enabled=false
      - cluster.name=elk-cluster
      - bootstrap.memory_lock=true
      - node.name=elasticsearch1
      - discovery.seed_hosts=elasticsearch2,elasticsearch3
      - cluster.initial_master_nodes=elasticsearch1,elasticsearch2,elasticsearch3
    mem_limit: 2g
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    networks:
      - es-stack

  elasticsearch2:
    image: elasticsearch:8.12.1
    container_name: elasticsearch2
    volumes:
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      - ES_JAVA_OPTS=-Xms1024m -Xmx1024m
      - xpack.security.enabled=false
      - cluster.name=elk-cluster
      - bootstrap.memory_lock=true
      - node.name=elasticsearch2
      - discovery.seed_hosts=elasticsearch1,elasticsearch3
      - cluster.initial_master_nodes=elasticsearch1,elasticsearch2,elasticsearch3
    mem_limit: 2g
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9201:9200"
    networks:
      - es-stack

  elasticsearch3:
    image: elasticsearch:8.12.1
    container_name: elasticsearch3
    volumes:
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      - ES_JAVA_OPTS=-Xms1024m -Xmx1024m
      - xpack.security.enabled=false
      - cluster.name=elk-cluster
      - bootstrap.memory_lock=true
      - node.name=elasticsearch3
      - discovery.seed_hosts=elasticsearch1,elasticsearch2
      - cluster.initial_master_nodes=elasticsearch1,elasticsearch2,elasticsearch3
    mem_limit: 2g
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9202:9200"
    networks:
      - es-stack

  logstash:
    image: logstash:8.12.1
    container_name: logstash
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/mysql-connector-j-8.3.0.jar:/usr/share/logstash/mysql-connector-j-8.3.0.jar
      - ./logstash/last_run_metadata:/usr/share/logstash/last_run_metadata
      - ./logstash/pipeline:/usr/share/logstash/pipeline
      - ./logstash/config/pipelines.yml:/usr/share/logstash/config/pipelines.yml
      - ./logstash/template:/usr/share/logstash/template
    depends_on:
      - elasticsearch1
      - elasticsearch2
      - elasticsearch3
      - elk-mysql
    networks:
      - es-stack

  elk-mysql:
    image: mysql:8.3.0
    restart: always
    container_name: elk-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: esstack
    ports:
      - "4556:3306"
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - es-stack

  kibana:
    image: kibana:8.12.1
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch1:9200
    ports:
      - "5601:5601"
    networks:
      - es-stack
    depends_on:
      - elasticsearch1

networks:
  es-stack:
    external: true

